[profile.default]
solc           = "0.8.26"
bytecode_hash  = "none"
viaIR = false
show_progress = true
optimizer_runs = 0xffffffff
verbosity      = 3
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
ast = true
evm_version    = "cancun"

ignored_error_codes = [
  2394, # Transient storage warning
  3860, # Initcode size too large
  5574  # Contract size too large
]

remappings = [
  "solady/src/=lib/solady/src/",
  "v4-core/src/=lib/v4-core/src/",
  "solmate/=lib/solmate/"
]

[profile.default.fmt]
line_length = 100


[profile.default.invariant]
fail_on_revert = true
depth = 200
runs = 256

[profile.ci]
show_progress = false

[profile.ci.invariant]
fail_on_revert = true
depth = 50
runs = 50

[profile.light-fuzz.invariant]
runs = 10
depth = 100

[profile.heavy-fuzz.invariant]
runs = 200
